In [ ]:
# # install octave
# !sudo apt-get -qq update
# !sudo apt-get -qq install octave octave-signal liboctave-dev

# # install oct2py that compatible with colab
# import os

# from pkg_resources import get_distribution

# os.system(
#     f"pip install -qq"
#     f" ipykernel=={get_distribution('ipykernel').version}"
#     f" ipython=={get_distribution('ipython').version}"
#     f" tornado=={get_distribution('tornado').version}"
#     f" oct2py"
# )

# # install packages
# !pip install -qq matpower matpowercaseframes

# Impedance Refactor for Parallel Lines

## Objective
To model a single impedance $ Z $ as $ N $ parallel lines in a power system data file.

## Formula

### Impedance

For $ N $ parallel lines with equal impedance:

$$
\frac{1}{Z_{\text{total}}} = \frac{1}{Z_1} + \frac{1}{Z_2} + \dots + \frac{1}{Z_n} = \frac{N}{Z_1} \quad \Rightarrow \quad Z_{\text{total}} = \frac{Z_1}{N}
$$

To refactor the impedance for each line, multiply the original impedance $ Z $ by $ N $:

$$
Z_n = Z \times N
$$

Where $ Z = R + jX $ (resistance and reactance).

### Susceptance

For $ N $ parallel lines with equal susceptance:

$$
B_{\text{total}} = B_1 + B_2 + \dots + B_n = N \times B_1
$$

To refactor the susceptance for each line, divide the original susceptance $ B $ by $ N $:

$$
B_{\text{new}} = \frac{B}{N}
$$

### Rate

For $ N $ parallel lines with equal rate $ C $:

$$
C_{\text{total}} = C_{1} + C_{2} + \dots + C_{n} = N \times C_1
$$

To refactor the rate for each line, divide the original rate $ C $ by $ N $:

$$
C_n = \frac{C}{N}
$$

Where $ C $ long term, short term and emergency rating in MVA.

## Example
Original impedance $ Z = 0.01 + j0.02 $ with line capacity $ C = 75 $ and total line charging susceptance $ B = 0.15$ , splitted into three parallel lines $ N = 3 $:

$$
Z_{\text{new}} = Z \times N = (0.01 + j0.02) \times 3 = 0.03 + j0.06
$$

$$
B_{\text{new}} = B / N = 0.15 / 3 = 0.05
$$

$$
C_{\text{new}} = C / N = 75 / 3 = 25
$$

We then have N row in branch data, with each using $ Z_{\text{new}} $, $ B_{\text{new}} $, and $ C_{\text{new}} $.

## Understanding Parallel Line

$$
Y_{total} = Y_1 + Y_2 + \dots + Y_n
$$

In [ ]:
import matpowercaseframes
import oct2py

import matpower

print(f"matpowercaseframes version: {matpowercaseframes.__version__}")
print(f"oct2py version: {oct2py.__version__}")

print(f"matpower version: {matpower.__version__}")

matpowercaseframes version: 2.0.1
oct2py version: 5.8.0
matpower version: 8.1.0.2.2.4

In [ ]:
import os

import pandas as pd
from matpowercaseframes import CaseFrames
from matpowercaseframes.constants import COLUMNS

from matpower import path_matpower, start_instance

## Inspect data

In [ ]:
m = start_instance()

In [ ]:
path = os.path.join(path_matpower, "data/case9.m")
cf = CaseFrames(path, load_case_engine=m)
cf.infer_numpy()
cf.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
1,1,4,0.0000,0.0576,0.000,250,250,250,0,0,1,-360,360
2,4,5,0.0170,0.0920,0.158,250,250,250,0,0,1,-360,360
3,5,6,0.0390,0.1700,0.358,150,150,150,0,0,1,-360,360
4,3,6,0.0000,0.0586,0.000,300,300,300,0,0,1,-360,360
5,6,7,0.0119,0.1008,0.209,150,150,150,0,0,1,-360,360
6,7,8,0.0085,0.0720,0.149,250,250,250,0,0,1,-360,360
7,8,2,0.0000,0.0625,0.000,250,250,250,0,0,1,-360,360
8,8,9,0.0320,0.1610,0.306,250,250,250,0,0,1,-360,360
9,9,4,0.0100,0.0850,0.176,250,250,250,0,0,1,-360,360

## Run base

In [ ]:
mpc_org = cf.to_mpc()
sol = m.runpf(mpc_org, verbose=True)

MATPOWER Version 8.1.1-dev, 25-Sep-2025
Power Flow -- AC-polar-power formulation

Newton's method converged in 4 iterations.
PF successful

Converged in 0.09 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    319.6              22.8
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches           9     Losses (I^2 * Z)         4.64             48.38
Transformers       0     Branch Charging (inj)     -              140.5
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   0.996 p.u. @ bus 9          1.040 p.u. @ bus 1
Voltage Angle      -3.99 deg   @ bus 9          9.28 deg   @ bus 2
P Losses (I^2*R)             -                  2.30 MW    @ line 8-9
Q Losses (I^2*X)             -                 15.83 MVAr  @ line 8-2

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
----- ------- --------  --------  --------  --------  --------
    1  1.040    0.000*    71.64     27.05       -         -
    2  1.025    9.280    163.00      6.65       -         -
    3  1.025    4.665     85.00    -10.86       -         -
    4  1.026   -2.217       -         -         -         -
    5  1.013   -3.687       -         -       90.00     30.00
    6  1.032    1.967       -         -         -         -
    7  1.016    0.728       -         -      100.00     35.00
    8  1.026    3.720       -         -         -         -
    9  0.996   -3.989       -         -      125.00     50.00
                        --------  --------  --------  --------
               Total:    319.64     22.84    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     71.64     27.05    -71.64    -23.92     0.000      3.12
   2      4      5     30.70      1.03    -30.54    -16.54     0.166      0.90
   3      5      6    -59.46    -13.46     60.82    -18.07     1.354      5.90
   4      3      6     85.00    -10.86    -85.00     14.96     0.000      4.10
   5      6      7     24.18      3.12    -24.10    -24.30     0.088      0.75
   6      7      8    -75.90    -10.70     76.38     -0.80     0.475      4.03
   7      8      2   -163.00      9.18    163.00      6.65     0.000     15.83
   8      8      9     86.62     -8.38    -84.32    -11.31     2.300     11.57
   9      9      4    -40.68    -38.69     40.94     22.89     0.258      2.19
                                                             --------  --------
                                                    Total:     4.641     48.38

In [ ]:
pd.DataFrame(sol["branch"], columns=COLUMNS["branch"][:17])

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX,PF,QF,PT,QT
0,1.0,4.0,0.0000,0.0576,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,71.641021,27.045924,-71.641021,-23.923127
1,4.0,5.0,0.0170,0.0920,0.158,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,30.703670,1.030006,-30.537263,-16.543365
2,5.0,6.0,0.0390,0.1700,0.358,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,-59.462737,-13.456635,60.816586,-18.074836
3,3.0,6.0,0.0000,0.0586,0.000,300.0,300.0,300.0,0.0,0.0,1.0,-360.0,360.0,85.000000,-10.859709,-85.000000,14.955327
4,6.0,7.0,0.0119,0.1008,0.209,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,24.183414,3.119508,-24.095417,-24.295823
5,7.0,8.0,0.0085,0.0720,0.149,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-75.904583,-10.704177,76.379866,-0.797331
6,8.0,2.0,0.0000,0.0625,0.000,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-163.000000,9.178149,163.000000,6.653660
7,8.0,9.0,0.0320,0.1610,0.306,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,86.620134,-8.380817,-84.320163,-11.312751
8,9.0,4.0,0.0100,0.0850,0.176,250.0,250.0,250.0,0.0,0.0,1.0,-360.0,360.0,-40.679837,-38.687249,40.937352,22.893121

## Edit branch to became N parallel lines

In [ ]:
N = 2
cf.branch = pd.concat([cf.branch] * N, ignore_index=True)
cols = ["BR_R", "BR_X", "BR_B", "RATE_A", "RATE_B", "RATE_C"]
cf.branch[cols] = cf.branch[cols].astype(float)
cf.branch.loc[:, ["BR_R", "BR_X"]] = cf.branch.loc[:, ["BR_R", "BR_X"]] * N
cf.branch.loc[:, ["BR_B", "RATE_A", "RATE_B", "RATE_C"]] = (
    cf.branch.loc[:, ["BR_B", "RATE_A", "RATE_B", "RATE_C"]] / N
)
cf.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1,4,0.0000,0.1152,0.0000,125.0,125.0,125.0,0,0,1,-360,360
1,4,5,0.0340,0.1840,0.0790,125.0,125.0,125.0,0,0,1,-360,360
2,5,6,0.0780,0.3400,0.1790,75.0,75.0,75.0,0,0,1,-360,360
3,3,6,0.0000,0.1172,0.0000,150.0,150.0,150.0,0,0,1,-360,360
4,6,7,0.0238,0.2016,0.1045,75.0,75.0,75.0,0,0,1,-360,360
5,7,8,0.0170,0.1440,0.0745,125.0,125.0,125.0,0,0,1,-360,360
6,8,2,0.0000,0.1250,0.0000,125.0,125.0,125.0,0,0,1,-360,360
7,8,9,0.0640,0.3220,0.1530,125.0,125.0,125.0,0,0,1,-360,360
8,9,4,0.0200,0.1700,0.0880,125.0,125.0,125.0,0,0,1,-360,360
9,1,4,0.0000,0.1152,0.0000,125.0,125.0,125.0,0,0,1,-360,360
10,4,5,0.0340,0.1840,0.0790,125.0,125.0,125.0,0,0,1,-360,360
11,5,6,0.0780,0.3400,0.1790,75.0,75.0,75.0,0,0,1,-360,360
12,3,6,0.0000,0.1172,0.0000,150.0,150.0,150.0,0,0,1,-360,360
13,6,7,0.0238,0.2016,0.1045,75.0,75.0,75.0,0,0,1,-360,360
14,7,8,0.0170,0.1440,0.0745,125.0,125.0,125.0,0,0,1,-360,360
15,8,2,0.0000,0.1250,0.0000,125.0,125.0,125.0,0,0,1,-360,360
16,8,9,0.0640,0.3220,0.1530,125.0,125.0,125.0,0,0,1,-360,360
17,9,4,0.0200,0.1700,0.0880,125.0,125.0,125.0,0,0,1,-360,360

In [ ]:
mpc_new = cf.to_mpc()
sol = m.runpf(mpc_new, verbose=True)

MATPOWER Version 8.1.1-dev, 25-Sep-2025
Power Flow -- AC-polar-power formulation

Newton's method converged in 4 iterations.
PF successful

Converged in 0.05 seconds
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    319.6              22.8
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches          18     Losses (I^2 * Z)         4.64             48.38
Transformers       0     Branch Charging (inj)     -              140.5
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   0.996 p.u. @ bus 9          1.040 p.u. @ bus 1
Voltage Angle      -3.99 deg   @ bus 9          9.28 deg   @ bus 2
P Losses (I^2*R)             -                  1.15 MW    @ line 8-9
Q Losses (I^2*X)             -                  7.92 MVAr  @ line 8-2

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
----- ------- --------  --------  --------  --------  --------
    1  1.040    0.000*    71.64     27.05       -         -
    2  1.025    9.280    163.00      6.65       -         -
    3  1.025    4.665     85.00    -10.86       -         -
    4  1.026   -2.217       -         -         -         -
    5  1.013   -3.687       -         -       90.00     30.00
    6  1.032    1.967       -         -         -         -
    7  1.016    0.728       -         -      100.00     35.00
    8  1.026    3.720       -         -         -         -
    9  0.996   -3.989       -         -      125.00     50.00
                        --------  --------  --------  --------
               Total:    319.64     22.84    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     35.82     13.52    -35.82    -11.96     0.000      1.56
   2      4      5     15.35      0.52    -15.27     -8.27     0.083      0.45
   3      5      6    -29.73     -6.73     30.41     -9.04     0.677      2.95
   4      3      6     42.50     -5.43    -42.50      7.48     0.000      2.05
   5      6      7     12.09      1.56    -12.05    -12.15     0.044      0.37
   6      7      8    -37.95     -5.35     38.19     -0.40     0.238      2.01
   7      8      2    -81.50      4.59     81.50      3.33     0.000      7.92
   8      8      9     43.31     -4.19    -42.16     -5.66     1.150      5.79
   9      9      4    -20.34    -19.34     20.47     11.45     0.129      1.09
  10      1      4     35.82     13.52    -35.82    -11.96     0.000      1.56
  11      4      5     15.35      0.52    -15.27     -8.27     0.083      0.45
  12      5      6    -29.73     -6.73     30.41     -9.04     0.677      2.95
  13      3      6     42.50     -5.43    -42.50      7.48     0.000      2.05
  14      6      7     12.09      1.56    -12.05    -12.15     0.044      0.37
  15      7      8    -37.95     -5.35     38.19     -0.40     0.238      2.01
  16      8      2    -81.50      4.59     81.50      3.33     0.000      7.92
  17      8      9     43.31     -4.19    -42.16     -5.66     1.150      5.79
  18      9      4    -20.34    -19.34     20.47     11.45     0.129      1.09
                                                             --------  --------
                                                    Total:     4.641     48.38

In [ ]:
pd.DataFrame(sol["branch"], columns=COLUMNS["branch"][:17])

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX,PF,QF,PT,QT
0,1.0,4.0,0.0000,0.1152,0.0000,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,35.820511,13.522962,-35.820511,-11.961563
1,4.0,5.0,0.0340,0.1840,0.0790,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,15.351835,0.515003,-15.268631,-8.271683
2,5.0,6.0,0.0780,0.3400,0.1790,75.0,75.0,75.0,0.0,0.0,1.0,-360.0,360.0,-29.731369,-6.728317,30.408293,-9.037418
3,3.0,6.0,0.0000,0.1172,0.0000,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,42.500000,-5.429855,-42.500000,7.477664
4,6.0,7.0,0.0238,0.2016,0.1045,75.0,75.0,75.0,0.0,0.0,1.0,-360.0,360.0,12.091707,1.559754,-12.047709,-12.147911
5,7.0,8.0,0.0170,0.1440,0.0745,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-37.952291,-5.352089,38.189933,-0.398666
6,8.0,2.0,0.0000,0.1250,0.0000,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-81.500000,4.589074,81.500000,3.326830
7,8.0,9.0,0.0640,0.3220,0.1530,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,43.310067,-4.190409,-42.160081,-5.656376
8,9.0,4.0,0.0200,0.1700,0.0880,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-20.339919,-19.343624,20.468676,11.446560
9,1.0,4.0,0.0000,0.1152,0.0000,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,35.820511,13.522962,-35.820511,-11.961563
10,4.0,5.0,0.0340,0.1840,0.0790,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,15.351835,0.515003,-15.268631,-8.271683
11,5.0,6.0,0.0780,0.3400,0.1790,75.0,75.0,75.0,0.0,0.0,1.0,-360.0,360.0,-29.731369,-6.728317,30.408293,-9.037418
12,3.0,6.0,0.0000,0.1172,0.0000,150.0,150.0,150.0,0.0,0.0,1.0,-360.0,360.0,42.500000,-5.429855,-42.500000,7.477664
13,6.0,7.0,0.0238,0.2016,0.1045,75.0,75.0,75.0,0.0,0.0,1.0,-360.0,360.0,12.091707,1.559754,-12.047709,-12.147911
14,7.0,8.0,0.0170,0.1440,0.0745,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-37.952291,-5.352089,38.189933,-0.398666
15,8.0,2.0,0.0000,0.1250,0.0000,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-81.500000,4.589074,81.500000,3.326830
16,8.0,9.0,0.0640,0.3220,0.1530,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,43.310067,-4.190409,-42.160081,-5.656376
17,9.0,4.0,0.0200,0.1700,0.0880,125.0,125.0,125.0,0.0,0.0,1.0,-360.0,360.0,-20.339919,-19.343624,20.468676,11.446560

## TODO: Show the new branch resiliency when there is branch contingency N - 1